import type { Theme } from '../theme';

const biminiBreeze: Theme = {
  id: 'bimini-breeze',
  name: 'Bimini Breeze',
  enabled: true,
  themeClass: 'light',
  themeLabel: 'L3',
  statusBarStyle: 'light',
  statusBarBg: '#004455',
  appBgLayer: { type: 'gradient', colors: ['#fdf5e0', '#c8f0e8', '#7dd8cc'], locations: [0, 0.6, 1] },
  scrollAreaBg: { type: 'solid', color: '#f0fbf7' },
  headerBg: '#c8f0e8',
  footerBg: null,
  headerBorder: '#8ecdc0',
  menuBg: '#f5fdfb',
  scrollAreaBorder: '#8ecdc0',
  checkboxBorder: '#8ecdc0',
  footerBorder: '#006655',
  separator: '#b0ddd4',
  listSelectorBg: '#dff5ee',
  listSelectorText: '#1a3a35',
  listSelectorBorder: '#00998a',
  text: '#1a3a35',
  textNote: '#2a7060',
  textDone: '#5c9088',
  textDepth: ['#1a3a35', '#2a7060', '#2a7060'],
  accent: '#00998a',
  danger: '#cc3300',
  iconColor: '#007766',
  priorityElevated: '#ff8800',
  priorityTop: '#cc2200',
  checkboxBg: '#f0fbf7',
  checkboxDoneBg: '#3d9e90',
  checkmarkColor: '#ffffff',
  iconGradient: null,
  fontFamily: null,
};

export default biminiBreeze;
