import type { Theme } from '../theme';

const defaultTheme: Theme = {
  id: 'default',
  name: 'Default',
  enabled: true,
  themeClass: 'light',
  themeLabel: 'L1',
  statusBarStyle: 'dark',
  statusBarBg: '#ffbe30',
  appBgLayer: { type: 'gradient', colors: ['#ffcb58', '#eeddba', '#ffbe30'], locations: [0, 0.5, 1] },
  scrollAreaBg: { type: 'solid', color: '#eae2ca' },
  headerBg: null,
  footerBg: null,
  headerBorder: '#d4b24d',
  menuBg: '#f0e8d5',
  scrollAreaBorder: '#025f96',
  checkboxBorder: '#c7ba9b',
  footerBorder: '#43350c',
  separator: '#d9ccb4',
  listSelectorBg: '#ffe8a9',
  listSelectorText: '#00395b',
  listSelectorBorder: '#025f96',
  text: '#3d2e21',
  textNote: '#725f4b',
  textDone: '#8a7260',
  textDepth: ['#1a1008', '#3d2e21', '#5a4535'],
  accent: '#6a3f1f',
  danger: '#9e3a2a',
  iconColor: '#025f96',
  priorityElevated: '#c96a00',
  priorityTop: '#b52a1a',
  checkboxBg: '#fffdf5',
  checkboxDoneBg: '#a87848',
  checkmarkColor: '#eae2ca',
  iconGradient: null,
  fontFamily: null,
};

export default defaultTheme;
