import type { Theme } from '../theme';

const muirLight: Theme = {
  id: 'muir-light',
  name: 'Muir Light',
  enabled: true,
  themeClass: 'light',
  themeLabel: 'L4',
  statusBarStyle: 'light',
  statusBarBg: '#0e1a14',
  appBgLayer: { type: 'image', source: require('../../assets/backgrounds/muir-light.png') },
  scrollAreaBg: { type: 'solid', color: '#162018f0' },
  headerBg: '#0e1a14',
  footerBg: null,
  headerBorder: '#0a140e',
  menuBg: '#1a2a1e',
  scrollAreaBorder: '#3a4a34',
  checkboxBorder: '#3a4a34',
  footerBorder: '#0a140e',
  separator: '#2a3a2a',
  listSelectorBg: '#1a2a1e',
  listSelectorText: '#e8dcb8',
  listSelectorBorder: '#d4a64a',
  text: '#e8dcb8',
  textNote: '#a8a080',
  textDone: '#5a5a44',
  textDepth: ['#e8dcb8', '#c4ba94', '#9a9268'],
  accent: '#d4a64a',
  danger: '#c8642a',
  iconColor: '#d4a64a',
  priorityElevated: '#d4a64a',
  priorityTop: '#c8642a',
  checkboxBg: '#0e1a14',
  checkboxDoneBg: '#d4a64a',
  checkmarkColor: '#0e1a14',
  iconGradient: null,
  fontFamily: null,
};

export default muirLight;
